import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { cartInput, customerInput, placeOrder, quote } from '../src/lib/server/checkout';
import type { Database } from '../src/lib/server/database';
import { POST as orderEndpoint } from '../src/app/api/orders/route';
import { POST as quoteEndpoint } from '../src/app/api/checkout/route';
async function main() {
const pg = new PGlite();
await pg.exec(await readFile('database/schema.sql','utf8'));
const db = pg as unknown as Database;
await pg.query("INSERT INTO voss_products VALUES('tassel-tote','Article 09','Tassel Tote','Tote','Totes',3100,true)");
await pg.query("INSERT INTO voss_variants VALUES('tassel-tote','cognac','Cognac','#9e5e30',true)");
await pg.query("INSERT INTO voss_images VALUES('tassel-tote','cognac',0,'/studio.webp','/white.webp','Front',960,1200)");
const items = [{slug:'tassel-tote',colour:'cognac',quantity:1,price:1}];
const customer = {name:'Test customer',phone:'03001234567',email:'',address:'Test address 12, Test street',city:'Lahore',province:'Punjab',postcode:'',notes:''};
assert.throws(()=>cartInput([{...items[0],quantity:-1}]));
assert.throws(()=>cartInput([{...items[0],quantity:15},{...items[0],quantity:15}]));
assert.throws(()=>customerInput({...customer,phone:'1234'}));
assert.equal(customerInput({...customer,phone:'+92 300 1234567'}).phone,'03001234567');
assert.equal(customerInput({...customer,city:' lahore '}).city,'Lahore');
assert.throws(()=>customerInput({...customer,city:'Karachi'}),/Lahore only/);
assert.throws(()=>customerInput({...customer,province:'Sindh'}),/Lahore only/);
const q = await quote(cartInput(items),db,250); assert.equal(q.total,3100); assert.equal(q.delivery,0);
const input = {items,customer,idempotencyKey:randomUUID(),expectedTotal:3100};
const [first,retry] = await Promise.all([placeOrder(input,db,250),placeOrder(input,db,250)]);
assert.equal(first.reference,retry.reference);
assert.equal((await pg.query<{used:number}>("SELECT used FROM voss_promotions")).rows[0].used,1);
await assert.rejects(()=>placeOrder({...input,customer:{...customer,name:'Changed'}},db,250),/already been used/);
await assert.rejects(()=>placeOrder({...input,idempotencyKey:randomUUID(),expectedTotal:1},db,250),/total has changed/);
await pg.query("UPDATE voss_promotions SET used=29");
const results = await Promise.allSettled([0,1].map(n=>placeOrder({...input,customer:{...customer,phone:`0300111111${n}`},idempotencyKey:randomUUID()},db,250)));
assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
assert.equal(results.filter(r=>r.status==='rejected').length,1);
assert.equal((await pg.query<{used:number}>("SELECT used FROM voss_promotions")).rows[0].used,30);
await assert.rejects(()=>quote(cartInput(items),db,null),/first 30 free-delivery orders/);
await assert.rejects(()=>placeOrder({...input,idempotencyKey:randomUUID()},db,null),/first 30 free-delivery orders/);
assert.equal((await placeOrder(input,db,null)).reference,first.reference);
const paid = await placeOrder({...input,idempotencyKey:randomUUID(),expectedTotal:3350},db,250);
assert.equal(paid.freeDelivery,false); assert.equal(paid.delivery,250);
assert.equal((await pg.query<{used:number}>("SELECT used FROM voss_promotions")).rows[0].used,30);
await placeOrder({...input,idempotencyKey:randomUUID(),expectedTotal:3350},db,250);
await assert.rejects(()=>placeOrder({...input,idempotencyKey:randomUUID(),expectedTotal:3350},db,250),/already placed several/);
// Force a write failure after order insertion: the entire transaction must roll back.
await pg.query("UPDATE voss_promotions SET used=0");
await pg.exec("CREATE FUNCTION reject_test_item() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'simulated storage failure'; END; $$ LANGUAGE plpgsql; CREATE TRIGGER reject_item BEFORE INSERT ON voss_order_items FOR EACH ROW EXECUTE FUNCTION reject_test_item();");
const before = (await pg.query<{count:number}>('SELECT count(*)::int AS count FROM voss_orders')).rows[0].count;
await assert.rejects(()=>placeOrder({...input,customer:{...customer,phone:'03002222222'},idempotencyKey:randomUUID()},db,250),/simulated storage failure/);
assert.equal((await pg.query<{count:number}>('SELECT count(*)::int AS count FROM voss_orders')).rows[0].count,before);
assert.equal((await pg.query<{used:number}>('SELECT used FROM voss_promotions')).rows[0].used,0);
await pg.exec('DROP TRIGGER reject_item ON voss_order_items');
Object.assign(process.env, {VOSS_LOCAL_DATABASE:'1',VOSS_CHECKOUT_ENABLED:'true',VOSS_PAYMENT_METHOD:'cod',VOSS_DELIVERY_FEE_PKR:'',VOSS_DELIVERY_CITY:'Lahore'});
(globalThis as typeof globalThis & {vossDatabase?: Promise<Database>}).vossDatabase = Promise.resolve(db);
const request = (body: unknown, origin = 'http://127.0.0.1:3000') => new Request('http://localhost:3000/api/orders', {method:'POST',headers:{host:'127.0.0.1:3000',origin,'content-type':'application/json'},body:JSON.stringify(body)});
const apiInput = {...input,idempotencyKey:randomUUID(),customer:{...customer,phone:'03003333333'},payment:'cod',consent:true};
assert.equal((await orderEndpoint(request(apiInput,'https://unrelated.example'))).status,403);
const apiQuote = await quoteEndpoint(request({items})); assert.equal(apiQuote.status,200); assert.equal((await apiQuote.json()).total,3100);
const apiOrder = await orderEndpoint(request(apiInput)); assert.equal(apiOrder.status,201);
assert.equal(apiOrder.headers.get('cache-control'),'no-store, private');
const receipt = await apiOrder.json();
assert.equal((await (await orderEndpoint(request(apiInput))).json()).reference,receipt.reference);
assert.equal((await orderEndpoint(request({...apiInput,payment:'card'}))).status,400);
assert.equal((await orderEndpoint(request({...apiInput,consent:false}))).status,400);
assert.equal((await orderEndpoint(request({...apiInput,customer:{...customer,city:'Karachi'}}))).status,400);
await pg.query("UPDATE voss_promotions SET used=29");
const launchResults=await Promise.allSettled([0,1].map(n=>placeOrder({...input,customer:{...customer,phone:`0300444444${n}`},idempotencyKey:randomUUID()},db,null)));
assert.equal(launchResults.filter(r=>r.status==='fulfilled').length,1);
assert.equal(launchResults.filter(r=>r.status==='rejected').length,1);
assert.equal((await pg.query<{used:number}>("SELECT used FROM voss_promotions")).rows[0].used,30);
const exhausted=await quoteEndpoint(request({items}));
assert.equal(exhausted.status,409);
assert.match((await exhausted.json()).error,/contact VOSS on WhatsApp/);
process.env.VOSS_CHECKOUT_ENABLED='false';
assert.equal((await orderEndpoint(request(apiInput))).status,503);
await pg.close();
console.log('PASS: validation, server prices, retry idempotency, final free-delivery slot concurrency, order 31 delivery, rate limit, transactional rollback. Test delivery fee only: Rs 250.');
console.log('PASS: HTTP order/quote handlers, cross-origin rejection, payment/consent checks, disabled checkout, no-store responses.');
console.log('PASS: Lahore-only addresses, launch-only order cap, safe retries after launch fills, concurrent final free order.');
}
main().catch(error => { console.error(error); process.exit(1); });
