'use client';
import { useEffect,useState } from 'react';
import type { SocialData,Post } from '@/lib/server/social';
const display=(n:number|null)=>n===null?'—':n.toLocaleString();
function safeLink(value:string){try{const u=new URL(value);return u.protocol==='https:'&&['instagram.com','www.instagram.com','facebook.com','www.facebook.com'].includes(u.hostname)?u.href:undefined;}catch{return undefined;}}
export function SocialInsights(){
  const [data,setData]=useState<SocialData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[sort,setSort]=useState('recent');
  async function refresh(){setBusy(true);setError('');try{const r=await fetch('/api/insights',{cache:'no-store',signal:AbortSignal.timeout(60000)});if(!r.ok)throw new Error('Social data could not be loaded. Sign in again if your session expired.');setData(await r.json());}catch(e){setError(e instanceof Error?e.message:'Social data unavailable.');}finally{setBusy(false);}}
  useEffect(()=>{void refresh();},[]);
  const posts=[...(data?.posts||[])].sort((a,b)=>sort==='recent'?Date.parse(b.published)-Date.parse(a.published):(b[sort as keyof Post] as number??-1)-(a[sort as keyof Post] as number??-1));
  return <section className="social-insights"><header><div><span className="v-kicker">Social performance</span><h2>Your posts, by the numbers.</h2></div><button onClick={refresh} disabled={busy}>{busy?'Checking Meta…':'Refresh metrics ↻'}</button></header><p>Views, reach and interactions from your connected accounts. No AI scoring or generated advice.</p>{error&&<p role="alert">{error}</p>}{data&&<><p><strong>{data.connected?'Account data received':'Connection pending'}</strong> · Checked {new Date(data.checkedAt).toLocaleString()}</p>{data.notices.map(n=><p className="social-note" key={n}>{n}</p>)}{posts.length>0&&<><label>Sort posts<select value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Most recent</option><option value="views">Most views</option><option value="engagement">Highest engagement by reach</option><option value="likes">Most likes / reactions</option></select></label><div className="social-posts">{posts.map(p=><article key={p.id} className="social-post"><span className="v-kicker">{p.platform}</span><p>{p.text.slice(0,240)||'Post without a caption'}</p><small>{p.published?new Date(p.published).toLocaleDateString():''}</small><dl><dt>Views</dt><dd>{display(p.views)}</dd><dt>Reach</dt><dd>{display(p.reach)}</dd><dt>{p.platform==='Facebook'?'Reactions':'Likes'}</dt><dd>{display(p.likes)}</dd><dt>Comments</dt><dd>{display(p.comments)}</dd><dt>Shares</dt><dd>{display(p.shares)}</dd><dt>Saves</dt><dd>{display(p.saved)}</dd><dt>Engagement / reach</dt><dd>{p.engagement===null?'—':`${p.engagement}%`}</dd></dl>{safeLink(p.url)&&<a href={safeLink(p.url)} target="_blank" rel="noreferrer">View post ↗</a>}</article>)}</div><small>Engagement by reach = (likes + comments + shares + saves) ÷ reach × 100. Shown only when all inputs are available. Metrics are cached for five minutes.</small></>}</>}</section>;
}
