import { ArrowIcon } from '@/components/ArrowIcon';
import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {CATALOGUE,getPiece,relatedPieces,coverImage} from '@/lib/catalogue';
import {ProductDetail} from '@/components/store/ProductDetail';
import {ProductCard} from '@/components/store/ProductCard';
export function generateStaticParams(){return CATALOGUE.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=getPiece(slug);return p?{title:`${p.name} in Pakistan`,description:`${p.note} Explore ${p.colourways.length} colours, view the photographs and see the price in PKR.`,...(process.env.NEXT_PUBLIC_SITE_URL?{alternates:{canonical:`/collection/${p.slug}`},openGraph:{images:[coverImage(p)]}}:{})}:{};}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=getPiece(slug);if(!p)notFound();const site=process.env.NEXT_PUBLIC_SITE_URL;return <main id="main"><nav className="v-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/collection">Collection</Link><span>/</span><span>{p.name}</span></nav>{site&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Product',name:p.name,description:p.note,image:new URL(coverImage(p),site).href,sku:p.dir,brand:{'@type':'Brand',name:'VOSS'},offers:{'@type':'Offer',price:p.price,priceCurrency:'PKR',url:new URL(`/collection/${p.slug}`,site).href}})}}/>}<ProductDetail piece={p}/><section className="v-section"><div className="v-section-heading"><div><span className="v-kicker">Another point of view</span><h2>Keep looking.</h2></div><Link href="/collection" className="v-text-link">The full collection <ArrowIcon direction="up-right" /></Link></div><div className="v-product-grid">{relatedPieces(p.slug,4).map(piece=><ProductCard key={piece.slug} piece={piece}/>)}</div></section></main>;}
